#3017760 - Support drush 9
EdisonLabs/database_sanitize pull request #12
Opened 2018-12-13 12:34 UTC by vijaycs85

Follow up of #9 

### Issue links

### Description

2018-12-13 15:02 UTC, manuee requested changes

2018-12-13 15:02 UTC, manuee commented on src/Commands/DatabaseSanitizeCommands.php
> + * Class DatabaseSanitizeCommands
I'm sure we can do better than this :smiley: 
```suggestion
 * Drush commands for Database Sanitize.
```

2018-12-13 15:02 UTC, manuee commented on src/Commands/DatabaseSanitizeCommands.php
> +   * Generate Sanitization entries.
```suggestion
   * Generates Sanitization entries for tables not specified on sanitize YML files..
```

2018-12-14 09:40 UTC, malcomio approved these changes

2018-12-14 10:40 UTC, manuee approved these changes

2018-12-14 10:40 UTC, merged